name: Build_Tag_on_PULL_REQUEST_to_release

on:
  pull_request:
    branches:
      - 'release'
      
permissions: write-all

jobs:
  build_apk_aab:
    if: startsWith(github.head_ref, 'releaze/') == true
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 11}
                  
      - name: Run static checks
        run: ./gradlew check    
          
      - name: Tag Release
        run: |
          branch_name=${GITHUB_HEAD_REF}
          version_name=${GITHUB_HEAD_REF##*/}
          echo "Head branch name: $branch_name"
          echo "Head version: $version_name"
          echo "Tagging release with tag $version_name"
          git tag $version_name
          git push origin --tags
