name: PR_ui_tests

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: {java-version: 11}
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
