name: PR_ui_tests

on:
  pull_request:
    branches:
      - 'main'

jobs:
  Unit-test:
    name: Run UI tests on PR in main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 11}
      - name: Run UI tests
        uses: faruktoptas/android-github-actions-emulator@latest
